config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :wishitems
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :wishitems, dependent: :destroy

  validates :username, presence: true
end

app/models/wishitem.rb
class Wishitem < ApplicationRecord
    belongs_to :user
    attachment :image
    
    with_options presence: true do
        validates :name
        validates :description
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    # protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: "Invalid Access"
    end 
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "Successfully updated your account information!"
    else
        render :edit
    end
  end

  private #this is to ensure params is only called within this controller
  def user_params
    params.require(:user).permit(:username, :name, :email)
  end

end

app/controllers/wishitems_controller.rb
class WishitemsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  protect_from_forgery :except => [:destroy]

  def index
    @wishitems = Wishitem.all
  end

  def show
    @wishitem = Wishitem.find(params[:id])
  end

  def new
    @wishitem = Wishitem.new
  end

  def create
    @wishitem = Wishitem.new(wishitem_params)
    @wishitem.user_id = current_user.id
    if @wishitem.save
      redirect_to wishitem_path(@wishitem), notice: "Successfully added item to your wishlist!"
    else
      render :new
    end
  end

  def edit
    @wishitem = Wishitem.find(params[:id])
    if @wishitem.user != current_user
      redirect_to wishitems_path, alert: "Invalid Access"
    end 
  end

  def update
    @wishitem = Wishitem.find(params[:id])
    if @wishitem.update(wishitem_params)
      redirect_to wishitem_path(@wishitem), notice: "Successfully updated item in your wishlist!"
    else
      render :edit
    end
  end

  def destroy
    wishitem = Wishitem.find(params[:id])
    wishitem.destroy
    redirect_to user_path(wishitem.user), notice: "Item is removed"
  end

  private
  def wishitem_params
    params.require(:wishitem)
    .permit(:name, :description, :link, :sponsored)
    .with_defaults(sponsored: false)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishitems_helper.rb
module WishitemsHelper
end

app/views/home/index.html.erb
<section class="section">
    <article class="media">
        <div class="media-content">
            <div class="content has-text-centered">
                <p>
                    <strong class="is-size-1" style="font-family: serif;">Welcome to <span class="has-text-danger">wishlist</span> 🪄</strong>
                </p>
                <h4>
                <span class="has-text-danger">Wishlist</span> lets you find out what your friends want as a gift for their special occasion! <br>
                You can also add items into your wishlist and share them with your friends!
                </h4>
            </div>
            <div class="columns is-centered">
                <div class="column is-5">
                
                </div>
            </div>
        </div>
    </article>
    <br>
    <div class="column is-centered">
        <div class="column">
            <div class="card-image has-text-centered">
                <figure class="image is-inline-block">
                    <%# <div class="main-image"> %>
                        <%= image_tag "gifts.png", class: "is-rounded" %>
                    <%# </div> %>
                </figure>    
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wishlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-dark">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-2 has-text-white" style="font-family: serif">wishlist</h1>
      <% end %>
      <div class="navbar-burger burger" data-target"navbarExampleTransparentExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
    <% if user_signed_in? %>
    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <div class="navbar-item">
        <div class="field is-grouped">
            <div class="control">
              <%= link_to "View All Wishes", wishitems_path, class: "navbar-item button is-primary has-text-grey" %>
            </div>
            <div class="control">
              <%= link_to "Add Your Wishlist", new_wishitem_path, class: "navbar-item button is-primary has-text-grey" %>
            </div>
        </div>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <div class="control">
              <%= link_to "View All Users", users_path, class: "button is-warning is-danger" %>
            </div>
            <div class="control">
              <%= link_to "My Page", user_path(current_user), class: "button is-warning is-danger" %>
            </div>
            <div class="control">
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-item button is-warning is-light" %>
            </div>
          </div>
        </div>
      </div>
      <% else %>
      <div id="navbarExampleTransparentExample">
        <div class="navbar-item">
        </div>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <div class="control">
              <%= link_to "Log in", new_user_session_path, class: "button is-warning is-light" %>
            </div>
            <div class="control">
              <%= link_to "Sign up", new_user_registration_path, class: "button is-warning is-light" %>
            </div>
          </div>
        </div>
      </div>

      <% end %>

      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<section class="hero is-small is-danger">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Edit User Information
      </h1>
    </div>
  </div>
</section>

<% if @user.errors.any? %>
    <div class="notification is-danger">
        <h2><%= pluralize(@user.errors.count, "error") %> There are some empty fields. </h2>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
        <div class="field">
            <%= f.label :username, "Nickname", class: "label" %>
            <%= f.text_field :username, class: "input" %>
        </div>

        <div class="field">
            <%= f.label :name, "Name", class: "label" %>
            <%= f.text_field :name, class: "input" %>
        </div>

        <div class="field">
            <%= f.label :email, "email", class: "label" %>
            <%= f.text_field :email, class: "input" %>
        </div>

        <%# <div class="field">
          <%= f.label :profile_image, "Profile Image", class: "label" %>
          <%# <%= f.attachment_field :profile_image, class: "input" %>
        <%# </div> %>

          <%= f.submit "Update", class: "button is-success" %>
        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-small is-danger">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                All Users
            </h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <% @users.each do |user| %>
            <div class="column is-3">
                <div class="card">
                    <div class="card-content">
                        <div class="card-image">
                            <figure class="image">
                                <%= link_to user_path(user) do %>
                                <%= attachment_image_tag user, :profile_image, fallback: "user.png" %>
                                <% end %>
                            </figure>
                        </div>
                    </div>
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <div class="title">
                                    <%= link_to user.username, user_path(user) %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</section>

app/views/users/show.html.erb
<section class="hero is-small is-danger">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                User Info
            </h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-8">
                <div class="columns is-centered">
                    <div class="column is-4">
                        <figure class="image is-128x128" style="margin-left: auto; margin-right: auto;">
                        <%= attachment_image_tag @user, :profile_image, fallback: "user.png" %>
                        </figure>
                    </div>
                    <div class="column is-8">
                        <table class="table is-fullwidth">
                            <tr>
                                <td class="is-size-4">
                                    <strong>
                                        <%= @user.username %>
                                    </strong>
                                </td>
                                <% if @user.id == current_user.id %>
                                <td class="is-size-4">
                                    <%= @user.name %>
                                </td>
                                <td class="is-size-4">
                                    <%= @user.email %>
                                </td>
                                <td>
                                <%= link_to "Edit", edit_user_path(@user), class: "button is-primary" %>
                                </td>
                                <% end %>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <% @user.wishitems.each do |wishitem| %>
            <div class="column is-3">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-square">
                            <%= link_to wishitem_path(wishitem) do %>
                            <%= attachment_image_tag wishitem, :image, fallback: "gift.png" %>
                            <% end %>
                        </figure>
                    </div>
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <div class="subtitle">
                                    <%= link_to wishitem_path(wishitem) do %>
                                    <strong>
                                    <%= wishitem.name %>
                                    </strong>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="media">
                        <div class="media-right">
                            <% if @user.id == current_user.id %>
                                <%= link_to edit_wishitem_path(wishitem), class: "panel-block" do %>
                                    <span class="panel-icon">
                                        <i class="fas fa-edit"></i>
                                    </span>
                                    Edit Item
                                <% end %>
                            <% end %>
                            <%# <%= button_to "Delete Item", wishitem_path(@wishitem), method: :delete, class: "button is-danger" %> 
                            <%# <%= link_to "Delete", wishitem_path(wishitem), method: :delete, data: {confirm: "Are you sure?"} %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
        </div>
    </div>
</section>

app/views/wishitems/edit.html.erb
<section class="hero is-small is-primary">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
            Edit Wish Item
            </h1>
        </div>
    </div>
</section>

<% if @wishitem.errors.any? %>
    <div class="notification is-danger">
        <h2><%= pluralize(@wishitem.errors.count, "error") %> There are some empty fields. </h2>
        <ul>
            <% @wishitem.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<section class="section">
    <div class="container">
        <div columns is-centered">
            <div class="column is-6">
                <%= form_for @wishitem do |f| %>
                <div class="field">
                    <%= f.label :name, "Product Name", class: "label" %>
                    <%= f.text_field :name, class: "input" %>
                </div>
                <div class="field">
                    <%= f.label :description, "Product Description", class: "label" %>
                    <%= f.text_area :description, class: "textarea" %>
                </div>
                <div class="field">
                    <%= f.label :link, "Link to Product", class: "label" %>
                    <%= f.text_field :link, class: "input" %>
                </div>
                <div class="columns is-mobile is-centered">
                    <div class="column is-narrow">
                        <p class="bd-notification is-primary">
                        <%= f.submit "Update", class: "button is-success" %>
                        </p>
                    </div>
                    <%# <div class="column is-narrow">
                        <p class="bd-notification is-primary">
                        <%= link_to "Delete Item", wishitem_path(@wishitem), method: :delete, class: "button is-danger" %>
                        <%# </p>
                    </div> %> 
                </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/wishitems/index.html.erb
<section class="hero is-small is-primary">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                All Wishlist Items
            </h1>
        </div>
    </div>
</section>


<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <% @wishitems.each do |wishitem| %>
            <div class="column is-3">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-left">
                                <figure class="image is-48x48">
                                <%= link_to user_path(wishitem.user.id) do %>
                                    <%= attachment_image_tag wishitem.user, :profile_image, fallback: "user.png" %>
                                    <% end %>
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="subtitle">
                                    <%= link_to wishitem.user.username, user_path(wishitem.user.id) %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-image">
                        <figure class="image is-square">
                        <%= link_to wishitem_path(wishitem) do %>
                            <%= attachment_image_tag wishitem, :image, fallback: "gift.png" %>
                        <% end %>
                        </figure>
                    </div>
                    <div class="card-content">
                        <div class="subtitle">
                            <strong>
                                <%= link_to wishitem.name, wishitem_path(wishitem) %>
                            </strong>
                        </div>
                    </div>
                    <div class="content">
                        <p class="has-text-grey">
                            Added on <%= wishitem.updated_at.strftime("%Y-%m-%d") %>
                        </p>
                    </div>
                </div>
            </div>
        <% end %>
        </div>
    </div>
</section>

app/views/wishitems/new.html.erb
<section class="hero is-small is-primary">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                Add Your Wishlist
            </h1>
        </div>
    </div>
</section>

<% if @wishitem.errors.any? %>
    <div class="notification is-danger">
        <h2><%= pluralize(@wishitem.errors.count, "error") %> There are some empty fields. </h2>
        <ul>
            <% @wishitem.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<section>
    <div class="container">
        <div class="column is-centered">
            <div class=column is-6">
                <%= form_for @wishitem do |f| %>
            
                <div class="field">
                    <%= f.label :name, "Product Name", class:"label" %>
                    <%= f.text_field :name, class: "input" %>
                </div>

                <div class="field">
                    <%= f.label :description, "Description", class: "label" %>
                    <%= f.text_area :description, class: "textarea" %>
                </div>

                <div class="field">
                    <%= f.label :link, "Link to Product <optional>", class: "label" %>
                    <%= f.text_field :link, class: "input" %>
                </div>

                <%# <div class="field"> %>
                    <%# <%= f.label :image, "Image", class: "label" %>
                    <%# <%= f.attachment_field :image, class: "input" %>
                <%# </div> %>

                <%= f.submit "Add to Wishlist", class: "button is-success" %>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/wishitems/show.html.erb
<section class="hero is-small is-primary">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                Wish Item
            </h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-3">
                <div class="card">
                    <div class="card-content">
                        <div class="content">
                            <%= link_to user_path(@wishitem.user) do %>
                            <h2 class="has-text-danger">
                                <%= @wishitem.user.username %>'s Wishlist
                            </h2>
                            <% end %>
                        </div>
                    </div>
                    <div class="card-image">
                        <figure class="image is-square">
                            <%= attachment_image_tag @wishitem, :image, fallback: "gift.png" %>
                        </figure>
                    </div>
                    <div class="card-content">
                        <div class="content">
                            <div class="media-content">
                                <p class="title is-4">
                                    <%= @wishitem.name %>
                                </p>
                            </div>
                        </div>
                        <div class="content">
                            <p>
                                <%= simple_format @wishitem.description %>
                            </p>
                                <% if @wishitem.link? %>
                            <p>
                                <%= link_to "Link to Product Page", @wishitem.link %>
                            </p>
                            <% end %>
                        </div>
                        <div class="media">
                            <div class="media-content">
                                <% if @wishitem.user.id == current_user.id %>
                                    <%= link_to edit_wishitem_path(@wishitem), class: "panel-block" do %>
                                        <span class="panel-icon">
                                            <i class="fas fa-edit"></i>
                                        </span>
                                        Edit Item
                                    <% end %>
                                <% end %>
                                <%# <%= button_to "Delete Item", wishitem_path(@wishitem), method: :delete, class: "button is-danger" %> 
                                <%# <%= link_to "Delete", wishitem_path(wishitem), method: :delete, data: {confirm: "Are you sure?"} %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>